# Generated by Django 5.2 on 2025-10-16 03:05

import uuid

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID do Favorito",
                    ),
                ),
                ("product_id", models.IntegerField(verbose_name="ID do Produto")),
                (
                    "product_data",
                    models.JSONField(
                        help_text="Dados do produto favorito em formato JSON",
                        verbose_name="Dados do Produto",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Produto Favorito",
                "verbose_name_plural": "Produtos Favoritos",
            },
        ),
        migrations.CreateModel(
            name="HistoricalFavorites",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid7,
                        editable=False,
                        verbose_name="ID do Favorito",
                    ),
                ),
                ("product_id", models.IntegerField(verbose_name="ID do Produto")),
                (
                    "product_data",
                    models.JSONField(
                        help_text="Dados do produto favorito em formato JSON",
                        verbose_name="Dados do Produto",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Produto Favorito",
                "verbose_name_plural": "historical Produtos Favoritos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
