# Generated by Django 5.2 on 2025-10-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_alter_customer_email_alter_historicalcustomer_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customer",
            name="unique_email_ci",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="historicalcustomer",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="E-mail"
            ),
        ),
    ]
